### ISSUE TITLE
Fix bug where cube appears at (0,0,0), causing screen to flickr

### ISSUE THREAD

**Issue by onggunhao** [bitcoin-vr/bitcoin-vr#47]
@robin-k-wilson It's difficult for me to capture a photo of this, but there is this strange "flicker" when you see the visualization at https://data-vr.github.io/blockchain-vr-build/. When you look downwards, you see a cube showing up.

My half-baked guess is that ReactVR is rendering the cube at (0,0,0) before running the transform -> translate on it. But I could be wrong.

Would appreciate if you could take a crack at solving this issue!

**Comment by robin-k-wilson** [comment]
Quick fix: move our origin up, so the flickering happens below the user.
